title: Paul O'Dowd
description: Notes and reflections on robotics, teaching, and research.  The views and opinions expressed on this site are my own and do not reflect those of my employer or institution.
url: "https://paulodowd.github.io"
baseurl: ""
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
